### test futures price
GET https://finance.pae.baidu.com/selfselect/getstockquotation?all=1&isIndex=false&isBk=false&isBlock=false&isStock=false&isFutures=true&isForeign=false&code=AU888&stockType=ab&newFormat=1&market_type=ab&group=quotation_futures_minute&finClientType=pc

### test futures price
GET https://finance.pae.baidu.com/selfselect/getstockquotation?all=3&isIndex=false&isStock=false&isFutures=true&code=AU888&stockType=ab&newFormat=1&finClientType=pc&market_type=ab&group=quotation_futures_minute

#### 
POST https://finance.pae.baidu.com/selfselect/gettrenddata?all=1
Content-Type: application/x-www-form-urlencoded

stock=%5B%7B%22code%22%3A%22CU2409%22%2C%22market%22%3A%22ab%22%2C%22type%22%3A%22futures%22%7D%2C%7B%22code%22%3A%22SA409%22%2C%22market%22%3A%22ab%22%2C%22type%22%3A%22futures%22%7D%2C%7B%22code%22%3A%22FG409%22%2C%22market%22%3A%22ab%22%2C%22type%22%3A%22futures%22%7D%2C%7B%22code%22%3A%22JM888%22%2C%22market%22%3A%22ab%22%2C%22type%22%3A%22futures%22%7D%2C%7B%22code%22%3A%22M9888%22%2C%22market%22%3A%22ab%22%2C%22type%22%3A%22futures%22%7D%2C%7B%22code%22%3A%22SM888%22%2C%22market%22%3A%22ab%22%2C%22type%22%3A%22futures%22%7D%5D&finClientType=pc


####
GET https://d.10jqka.com.cn/v6/time/qh_FG2409/last.js
Referer: https://goodsfu.10jqka.com.cn/
Content-Type: application/json


#### 同花顺
GET https://fupage.10jqka.com.cn/futgwapi/api/market/basis/v2/trend_data?contract=ag2408&spot_index_id=-1

### 
GET https://fupage.10jqka.com.cn/futgwapi/api/f10/contract/v1/info?code=sa9999

###
GET https://api.jijinhao.com/sQuoteCenter/realTime.htm?code=JO_165681&_=1718636839611
Referer: https://www.cngold.org/

###
GET https://hq.sinajs.cn?list=nf_CU2408
Referer: https://finance.sina.com.cn
Content-Type: application/json